platform :ios, '8.0'
use_frameworks!

def app
    pod 'Alamofire', '~> 3.0'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

target 'Services' do
    app
end

target 'ServicesTests' do
    pod 'OHHTTPStubs'
    pod 'Quick'
    pod 'Nimble'
    app
end
